# {automatic_allocation_port}=自動的に割り当てられるポート番号
# {userid} = 学籍番号に置換される
# {classid} = 授業コードに置換される
version: '3'
services:
  mysql:
    image: mariadb:10.3
    volumes:
      - mysql-volume:/var/lib/mysql
      - $PWD/mariadb.d:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=exercise
      - MYSQL_USER=exercise
      - MYSQL_PASSWORD=exercise
    command:
      - "--max-statement-time=30"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=exercise
      - PMA_PASSWORD=exercise
    links:
      - mysql
    ports:
      - {automatic_allocation_port}:80
    volumes:
      - phpmyadmin-volume:/sessions
      - $PWD/phpmyadmin_conf/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
      - $PWD/upload:/etc/phpmyadmin/upload:ro
volumes:
  mysql-volume:
    driver: local
  phpmyadmin-volume:
    driver: local